package com.example.appkhambenh.ui.utils

object Address {
    fun ethnics(): ArrayList<String>{
        return arrayListOf(
            "Kinh",
            "Mường",
            "Thổ",
            "Chứt",
            "Tày",
            "Giáy",
            "Nùng",
            "Sán Chay",
            "Cao Lan",
            "La Hủ",
            "La Chí",
            "Pà Thẻn",
            "Chơ Ro",
            "Kháng",
            "Lự",
            "Lô Lô",
            "Phù Lá",
            "Mảng",
            "Co",
            "Xinh Mun",
            "Hà Nhì",
            "Chu Ru",
            "Lào",
            "La",
            "Pu Péo",
            "Brâu",
            "Ơ Đu",
            "Rơ Măm",
            "Ngái",
            "Si La",
            "Pu Thê",
            "Cờ Lao",
            "La Ha",
            "Pà Di",
            "Cống",
            "Ro Mam",
            "Bố Y",
            "La Hu",
            "Đu",
            "Va",
            "Chơ Đăng",
            "Krông",
            "Mạ",
            "Ươi",
            "Ta Ôi",
            "Cơ Tu",
            "Giẻ Triêng",
            "Ma",
            "Hrê",
            "Ca Dong",
            "Chứt",
            "Mnông",
            "Xơ Đăng",
            "Sán Dìu",
            "Thái",
            "Khơ Mú",
            "Bru - Vân Kiều",
            "Cơ Ho",
            "Giá Rai",
            "Tà Ôi"
        )
    }

    fun nationality(): ArrayList<String>{
        return arrayListOf(
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua và Barbuda",
            "Argentina",
            "Armenia",
            "Úc",
            "Áo",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Bỉ",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia và Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Campuchia",
            "Cameroon",
            "Canada",
            "Cộng hòa Trung Phi",
            "Chad",
            "Chile",
            "Trung Quốc",
            "Colombia",
            "Comoros",
            "Congo, Cộng hòa Dân chủ",
            "Congo, Cộng hòa",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Síp",
            "Cộng hòa Séc",
            "Đan Mạch",
            "Djibouti",
            "Dominica",
            "Cộng hòa Dominica",
            "Đông Timor",
            "Ecuador",
            "Ai Cập",
            "El Salvador",
            "Guinea Xích Đạo",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Fiji",
            "Phần Lan",
            "Pháp",
            "Gabon",
            "Gambia",
            "Georgia",
            "Đức",
            "Ghana",
            "Hy Lạp",
            "Grenada",
            "Guatemala",
            "Mĩ",
            "Anh",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "Ấn Độ",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Ý",
            "Jamaica",
            "Nhật Bản",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kuwait",
            "Kyrgyzstan",
            "Lào",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Việt Nam",
            "Thái Lan",
            "Mozambique",
            "Myanmar (Miến Điện)",
            "Namibia",
            "Nauru",
            "Nepal",
            "Hà Lan",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Bắc Macedonia",
            "Na Uy",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Ba Lan",
            "Bồ Đào Nha",
            "Qatar",
            "Romania",
            "Nga",
            "Rwanda",
            "Saint Kitts và Nevis",
            "Saint Lucia",
            "Saint Vincent và Grenadines",
            "Samoa",
            "San Marino",
            "São Tomé và Príncipe",
            "Ả Rập Saudi",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Quần đảo Solomon",
            "Somalia",
            "Nam Phi",
            "Hàn Quốc",
            "Nam Sudan",
            "Tây Ban Nha",
            "Sri Lanka",
            "Sud"
        )
    }

    fun job(): ArrayList<String>{
        return arrayListOf(
            "Nhân dân",
            "Giáo viên",
            "Việt kiều",
            "Giám đốc DN",
            "Trí thức",
            "Cán bộ hưu trí",
            "Thương binh",
            "Lực lượng vũ trang",
            "Tự do",
            "Sinh viên,học sinh",
            "Ngân hàng",
            "Công nhân",
            "Nông dân",
            "Trẻ em dưới 6 tuổi",
            "Hành chính, sự nghiệp",
            "Nhân viên",
            "Công chức",
            "Lái xe",
            "Công an",
            "Thợ mộc",
            "Thợ cơ khí",
            "Phi công",
            "Kế toán",
            "Kinh doanh",
            "Hưu trí và trên 60 tuổi",
            "Bộ đội",
            "Kỹ sư",
            "Y tế",
            "Dịch vụ, buôn bán",
            "Ngoại kiều",
            "Khác",
            "Cựu chiến binh"
        )
    }
}