package com.example.appkhambenh.ui.utils

object PreferenceKey {
    var USER_ID = "USER_ID"
    var USER_NAME = "USER_NAME"
    var USER_BIRTH = "USER_BIRTH"
    var USER_AVATAR = "USER_AVATAR"
    var USER_PHONE = "USER_PHONE"
    var USER_ADDRESS = "USER_ADDRESS"
    var USER_EMAIL = "USER_EMAIL"
    var FORGET_PASSWORD = "FORGET_PASSWORD"
    var EMAIL = "EMAIL"
    var PASSWORD = "PASSWORD"
    var CHECK_LOGIN = "CHECK_LOGIN"
    var LIST_POSITION_HOUR = "LIST_POSITION_HOUR"
    var DATE_APPOINTMENT = "DATE_APPOINTMENT"
    var HOUR_APPOINTMENT = "HOUR_APPOINTMENT"
}